### ISSUE TITLE
  Navigator.pushNamed

### ISSUE THREAD

**Issue by vvagnersilva** [retroportalstudio/multilevel_drawer#3]
MLMenuItem(
                  leading: Icon(Icons.arrow_forward_ios),
                  content: Text("Usuário - Equipes & Locais"),
                  onClick: () {
                    // Ir para tela de cadastro de equipes
                    Navigator.pushNamed(context, '/equipe');
                  },

when calling a menu item the error below occurs

E/flutter ( 5466): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.
E/flutter ( 5466): Receiver: null
E/flutter ( 5466): Tried calling: focusScopeNode
E/flutter ( 5466): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 5466): #1      Route.didPush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:139:17)
E/flutter ( 5466): #2      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 5466): #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 5466): #4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 5466): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 5466): #6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 5466): #7      Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter ( 5466): #8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter ( 5466): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 5466): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 5466): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 5466): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 5466): #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 5466): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)

**Comment by retroportalstudio** [comment]
Solved!
