### ISSUE TITLE
when i adding  more then 5 ML submenu it getting overflow error

### ISSUE THREAD

**Issue by jamuflutterer** [retroportalstudio/multilevel_drawer#8]
[https://codeapprun.io/jayamurugan/widget/wvuTJgFpXS](url)

![image](https://user-images.githubusercontent.com/69213920/89328488-19deb980-d6ab-11ea-99b6-da00673b4d9b.png)

![image](https://user-images.githubusercontent.com/69213920/89328544-2d8a2000-d6ab-11ea-83cf-64930e67e11d.png)

i con't able to scroll it and view the menu and its sub menus.
i try to fix it with listview widget . but no result

**Comment by rijopp** [comment]
This is the same issue i faced

**Comment by ahmedelnahel** [comment]
same here, any solution?

**Comment by retroportalstudio** [comment]
Issue has been resolved, will push it at my earliest conv. !

**Comment by jamuflutterer** [comment]
thank you 👍

**Comment by jamuflutterer** [comment]
source code link pls

**Comment by jamuflutterer** [comment]
[image: image.png]i
i was added 6 submenu item but i only able to see 3. con't able to
scroll and view it.

**Comment by davidmednikov** [comment]
Can we please get the fix pushed to Github and pub.dev?

**Comment by pretech86** [comment]
i face the same issue , how can i solve it please

**Comment by TafadzwaD** [comment]
Was anyone able to solve this issue??

**Comment by shabeenabarde** [comment]
Anyone with a fix??

**Comment by smith123paul** [comment]
hello... its 2021... but here in the future, i havent recieved any fix.. please anyone with a fix,, otherwise you have a good code but make it scrollable please

**Comment by shabeenabarde** [comment]
Is there an alternative to this package coz seems like there is no fix.. And my client wants to see the app!

**Comment by retroportalstudio** [comment]
Apologies for the delay! Multilevel Drawer Version 2.0.0 has been pushed to GitHub with some major upgrades and migration to null safety. Few other fixes on the way. Thanks

**Comment by shabeenabarde** [comment]
> Apologies for the delay! Multilevel Drawer Version 2.0.0 has been pushed to GitHub with some major upgrades and migration to null safety. Few other fixes on the way. Thanks

Thanks for the update! Works fine!

**Comment by retroportalstudio** [comment]
Closing
